language: android
android:
  components:
    - build-tools-19.1.0
    - extra-android-support
    - extra-android-m2repository
before_install:
    - export TERM=dumb # to get clean gradle output
    - git submodule init && git submodule update

    # Create and start emulator
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
install: ./gradlew
before_script:
    - ./wait_for_emulator
script:
    - ./gradlew clean connectedAndroidTest

